### ISSUE TITLE
Map result format broken in 3.4.0

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMaps#118]
http://pastebin.com/zUKZD46B

--

Update: looks like none of the formats are showing up... https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk

Which is weird, since they are showing on the sandbox: http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Requ%C3%AAter

Perhaps the update on SMW wiki went bad... https://www.semantic-mediawiki.org/w/index.php?title=Special%3AVersion shows 3.4, yet a modification date in April

**Comment by Nikerabbit** [comment]
I am seeing the same thing after updating. Is #67 related? Could explain if sandbox is running a newer version of SMW.

**Comment by kghbln** [comment]
> Perhaps the update on SMW wiki went bad... https://www.semantic-mediawiki.org/w/index.php?title=Special%3AVersion shows 3.4, yet a modification date in April

No, it did not. Not all the info on "Special:Version" is updated instantaneously so it takes some time for the correct modification date to show up. It is now 2016-09-18.

> Could explain if sandbox is running a newer version of SMW.

Sandbox runs master, so yes. However sandbox is already on MW 1.27 whereas smw.o is still running MW 1.25.

**Comment by Nikerabbit** [comment]
I am running MW master myself though.

**Comment by JeroenDeDauw** [comment]
> Is #67 related?

Don't think so. This issue is likely caused by the refactoring I did to try find the "openlayers shows up as google maps" bug. Since the release I've merged https://github.com/SemanticMediaWiki/SemanticMaps/pull/112 into master, which touches the same code. Perhaps that fixed the issue. It would explain why sandbox is fine but SMW wiki is not. Could someone with the issue try running master or applying that change, or someone without the issue try running 3.4.0 and see if it makes a difference?

**Comment by kghbln** [comment]
> Is #67 related?

I do not think either since the change in SMW referring to this issue was included in SMW 2.4.1 which is powering s-mw.o.

> or someone without the issue try running 3.4.0 and see if it makes a difference?

Just downgraded sandbox to 3.4.0 and these are gone. @JeroenDeDauw Pls advise as soon as I should witch to master again.

**Comment by JeroenDeDauw** [comment]
Haha :D That's good news actually, as it means the issue has indeed been fixed by the PR I linked, meaning that all we need to do is tag master as 3.4.1 :)

This is quite ironic though... I left that change out of the release on purpose to not have undue risk of breaking things

**Comment by kghbln** [comment]
> This is quite ironic though... I left that change out of the release on purpose to not have undue risk of breaking things

Such is Jeroen. :) So ...

![proceed-cats-kitten-kitty-pic-picture-funny-lolcat-cute-fun-lovely-photo-images](https://cloud.githubusercontent.com/assets/1104078/18689473/9702430a-7f89-11e6-9662-ed2023ca4d86.jpg)

**Comment by JeroenDeDauw** [comment]
![proceed](https://cloud.githubusercontent.com/assets/146040/18689576/1fb08e00-7f8a-11e6-912b-d2a08b74fbe9.jpg)

**Comment by JeroenDeDauw** [comment]
This should be fixed now. Can someone confirm?

**Comment by Nikerabbit** [comment]
This rabbit confirms that 3.4.1 fixes this issue.

**Comment by JeroenDeDauw** [comment]
Thanks @Nikerabbit!

**Comment by JeroenDeDauw** [comment]
Do you by any chance have a public wiki that is now running that version? I'd like to verify some other things are fixed now as well. (Not having a development wiki makes certain things rather difficult ;p)
