### ISSUE TITLE
`kml' format: all the locations are doubled

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMaps#12]
Import from https://bugzilla.wikimedia.org/show_bug.cgi?id=32663

In case of `kml' format, every location is printed twice (every `<Placemark>' with all the content is doubled). The bug is specific for `kml' format, `map' format is not affected.

--  Van de Bugger 2011-11-26 19:53:57 UTC

**Comment by PeterTheOne** [comment]
Weird https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/51eebd42adcae55f935d31302827ad8e09a171f9/includes/storage/SMW_QueryResult.php#L293 and https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/5653a194fab284798fc4bd9ed6414a982e93c577/src/Query/QueryLinker.php#L48 are almost the same code.

**Comment by JeroenDeDauw** [comment]
I'm not sure what you mean. Context?

**Comment by PeterTheOne** [comment]
Here https://phabricator.wikimedia.org/T34663#368756 it is mentioned as the offending code..

**Comment by JeroenDeDauw** [comment]
>_> When you realize the issue is actually 5 years old already

**Comment by JeroenDeDauw** [comment]
I would expect a bug such as this one to lie within Semantic Maps, not SMW. Presumably in the KMLPrinter code

**Comment by JeroenDeDauw** [comment]
Now tracked at https://github.com/JeroenDeDauw/Maps/issues/238
