### ISSUE TITLE
Incorrect default zoom level for openlayers

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMaps#121]
If you go to https://dev.translatewiki.net/wiki/Map_of_translators (by ignoring the certificate warning), you will see a blue map, because it has maximum zoom in middle of ocean, instead of showing the whole world as the default googlemaps format does.

Using 3.4.1.

**Comment by JeroenDeDauw** [comment]
Presumably this is fixed by https://github.com/JeroenDeDauw/Maps/pull/234, which is not released yet. I'll see if I can make a bugfix release of Maps tomorrow.

**Comment by JeroenDeDauw** [comment]
I've tagged 3.8.2 now, so presumably this issue is fixed. If not, please create a new one at https://github.com/JeroenDeDauw/Maps/issues
