### ISSUE TITLE
Drop support for translations from translatewiki.net

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#122]
> Semantic Maps 3.4.x is the last release of Semantic Maps as a dedicated extension. It has been merged into the Maps extension, where development continues. All features available in Semantic Maps 3.4.x are available in Maps 4.0.x.

@Nikerabbit Translations will now roll in via the Maps extension, so translatewiki.net should no longer move in the translations here. Is there a best practice to preserve existing translations after the merge.

@JeroenDeDauw FYI

**Comment by Nikerabbit** [comment]
Will the SemanticMaps messages be merged to en/qqq.json of Maps or be in separete directory? I am assuming no messages will be renamed.

**Comment by JeroenDeDauw** [comment]
No messages will be renamed. I suppose merging them into a single file would be the most clean, though this can be done however you and other TWN people see fit. For such a merge, do I just merge the en messages into a single file, or should that be done differently?

**Comment by Nikerabbit** [comment]
Merging with existing en.json is sufficient. I just need to move the tags for optional messages to the other group then.

**Comment by Nikerabbit** [comment]
https://gerrit.wikimedia.org/r/#/c/312246/
