### ISSUE TITLE
Unexpected behaviour of #display_map:

### ISSUE THREAD

**Issue by heinrich-k** [SemanticMediaWiki/SemanticMaps#124]
Hello.
I currently run Semantic Map 3.1.3 and Maps 3.2

My code is
`{{#display_map:
|lines={{semantic template query}}
|centre=46.5,-34.5
|maxzoom=11
|minzoom=2
|zoom=3
|geoservice=geonames
|width=auto
|height=750px
|type=earth
|types=hybrid,earth,physical,satellite
}}`
The semantic query seem to generate output that is suitable for the lines= parameter. However, it appears as if there was some additional output that I can't see, but #display_map: tries to interpret, resulting in additional lines on the map.

How would I fix that ?

Best regards,
Heinrich

**Comment by kghbln** [comment]
Please open an issue for the [Maps extension](https://github.com/JeroenDeDauw/Maps/issues). Please also state the versions of MediaWiki and PHP when reporting as well as the versions of Semantic Maps and Maps which were able to render a correct map. I think there was a thread on the mailing list for this. If yes this one should probably be linked from the report too.

Actually I hardly use Semantic Maps / Maps so I cannot tell if there is a direct way to use the e.g. googlemaps format to do the voodoo you are describing here.
