### ISSUE TITLE
Template with Semantic Maps breaks Gallery/slideshow

### ISSUE THREAD

**Issue by d3mon187** [SemanticMediaWiki/SemanticMaps#15]
If you do an ask with format=maps and template=templatename, it seems to break an ask with format=gallery and widget=slideshow on the same page.   You just get the spinning icon instead of the image.  Not sure which is at fault, but it took me a while to figure out the combination causing the issue.  Template used doesn't seem to matter, as I tried one with just "hi", and it still broke.

MediaWiki 	1.22.2
Semantic Maps (Version 3.0.2)
Semantic MediaWiki (Version 1.9.1.1)
Maps (Version 3.0)

Appreciate any help tracking down the issue.

**Comment by PeterTheOne** [comment]
I can reproduce this: http://sandbox.semantic-mediawiki.org/wiki/Sad_Face

**Comment by kghbln** [comment]
Hmm, I tweaked the query a bit and now I get faces. Still an issue?

**Comment by PeterTheOne** [comment]
I also added the `widget=slideshow` and it still works.. I say we close this issue.

**Comment by kghbln** [comment]
Probably this was fixed en passant along the way. Could still be reopened though if we missed something here. Thanks for testing!
