### ISSUE TITLE
Markers will be stuck at the top in Internet Explorer

### ISSUE THREAD

**Issue by Flexmaen** [SemanticMediaWiki/SemanticMaps#2]
In the latest Internet Explorer versions (10, 11), the markers will not be shown at the correct position if zoom level is bigger than 15

(If you can't reproduce you might try with many markes and some of them outside the shown area - however screenshot is attached)

This happend with recend stable versions of Mediawiki, Semantic Mediawiki and Semantic Maps.

![gw_bug_ie2](https://f.cloud.github.com/assets/6330276/1850669/e2964918-76d8-11e3-8c16-17e6b46de5b9.png)

**Comment by JeroenDeDauw** [comment]
Using a newer version of OpenLayers, as per https://github.com/JeroenDeDauw/Maps/issues/88, might fix this issue.
