### ISSUE TITLE
Some tiles are loaded via http (and 404)

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMaps#21]
First of all, fantastic that openlayers works again; I've re-enabled it on translatewiki.net and the wiki looks much cleaner now.

But, why are some resources loaded over http when I browse in https?
Request 58: http://b.tile.openstreetmap.org/1/0/-1.png
Request 59: http://a.tile.openstreetmap.org/1/1/-1.png
http://www.webpagetest.org/result/140711_WE_R55/1/details/#request58

They also 404 in this example (and all those I saw recently), but I don't know how systematic is that.

**Comment by JeroenDeDauw** [comment]
Think this was fixed already
