### ISSUE TITLE
Custom Markers - Ability to display a different custom icon for each query result (enhancement)

### ISSUE THREAD

**Issue by c-ern** [SemanticMediaWiki/SemanticMaps#24]
In order to being able to distinguish each query result displayed on a map it would be great if each one was shown with the according icon.
I.e. one would search for fast food restaurants in a town, the location of McD would be displayed with its signature golden M, BK with its logo and so on.
One possibility to implement this would be to add a new attribute like "has custom_marker=mcd.png" to the corresponding page and add this ?has custom_marker to the ask-query.

**Comment by JeroenDeDauw** [comment]
Moved to https://github.com/JeroenDeDauw/Maps/issues/242
