### ISSUE TITLE
Multi-instance template with geographic coordinate with input type=map doesn't work

### ISSUE THREAD

**Issue by jqnatividad** [SemanticMediaWiki/SemanticMaps#25]
With MW 1.23.1, SMW 1.9.2, SF 2.8, SM 3.0.4 and Maps 3.1, input type=map doesn't work, but works fine outside a multi-instance template.
![define_knowledge_product__test_entry_55-5_-_knowledge_commons](https://cloud.githubusercontent.com/assets/1980690/4329822/03ac9710-3fa1-11e4-894a-9849165e16cc.jpg)

**Comment by Karlpietsch** [comment]
$( document ).ready( function() {
$( '.multipleTemplateAdder' ).click( function() {
	var $this = $( this );
	setTimeout(
		function() {
			$t = $this.closest( 'fieldset' ).find( '.multipleTemplateInstance' ).last();
			$g = $t.find( '.sminput-googlemaps3' ).first();
			$id = $g.attr('id');
                        inputname = $g.find('#' + $id + '_1_values').attr('name');
			$g.empty();
			maptemplate = 'Loading map form input...<div style="display:none" class="sminputdata">{"type":"ROADMAP","mappingservice":"googlemaps3","geoservice":"google","types":["ROADMAP","SATELLITE","HYBRID","TERRAIN"],"width":"400px","height":"350px","centre":false,"zoom":14,"layers":[],"controls":["pan","zoom","type","scale","streetview"],"zoomstyle":"DEFAULT","typestyle":"DEFAULT","autoinfowindows":false,"resizable":false,"kmlrezoom":false,"poi":true,"markercluster":false,"tilt":0,"imageoverlays":[],"kml":[],"gkml":[],"fusiontables":[],"searchmarkers":"","enablefullscreen":false,"fieldsize":40,"icon":"","locations":[],"geocodecontrol":true,"inputname":"__inputname__"}</div>';
			
			$g.html(maptemplate.replace("__inputname__",inputname));
			
			$g.googlemapsinput($id, jQuery.parseJSON($g.find('div').text()));
			
			
		},
		100
	);
} );
});
</script>

**Comment by JeroenDeDauw** [comment]
@Karlpietsch thanks for your suggestion. Can you submit it as a pull request?

**Comment by JeroenDeDauw** [comment]
Moved to https://github.com/JeroenDeDauw/Maps/issues/241
