### ISSUE TITLE
Map forminput doesn't work with HeaderTabs

### ISSUE THREAD

**Issue by jqnatividad** [SemanticMediaWiki/SemanticMaps#26]
As a workaround to #25, tried using HeaderTabs in a Form to prompt for 5 locations using a map input type, but it also doesn't work.

![define_knowledge_product__test_666_-_knowledge_commons](https://cloud.githubusercontent.com/assets/1980690/4361886/5bef38a8-4288-11e4-9ea4-b3d4bc42825e.jpg)

As soon as I resize the browser window though, it seems to work.  Maybe, triggering a map resize will help? (http://stackoverflow.com/questions/3014156/google-maps-and-jquery-tabs)

**Comment by JeroenDeDauw** [comment]
Moved to https://github.com/JeroenDeDauw/Maps/issues/240
