### ISSUE TITLE
How to use leaflet?

### ISSUE THREAD

**Issue by alexrj** [SemanticMediaWiki/SemanticMaps#30]
Hello! Thank you for your work.
I've got one question: how to use leaflet with SemanticMaps?
I tried to use `format=leaflet` with SemanticMaps 3.0.4 but it didn't work.

**Comment by krabina** [comment]
Jeroen it would be great I you could in some sentences scribble out what would bee needed to be done in order to achieve leaflet support in Semantic Maps...

**Comment by JeroenDeDauw** [comment]
To be honest I don't quite remember the details. But basically you need to register support of a new service for the QueryPrinter handling and/or the form input, depending on what you want to support.

https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/src/services/GoogleMaps3/SM_GoogleMaps3.php#L62

Just see what is in the services directory for Google maps. You need similar stuff, and not as much if you only care about queries and not forms.
