### ISSUE TITLE
Embedding own layers

### ISSUE THREAD

**Issue by markmuzenhardt** [SemanticMediaWiki/SemanticMaps#31]
I try to find out if there is a way to embed own openLayers compatible maps with SemanticMaps.

**Comment by krabina** [comment]
In my experience, Semantic Maps also (again) supports OpenLayers, at least in the master branch I tried out.

**Comment by JeroenDeDauw** [comment]
Really? Is this by doing format=map and having the default service on openlayers? In any case, you will certainly not have full support for it, since there is no openlayers form input defined.

**Comment by krabina** [comment]
format=openlayers
see here: http://standards.kdz.eu/index.php?title=MapsTestWien#Openlayers

**Comment by markmuzenhardt** [comment]
@krabina: How did you get the Vienna Map into semantic-maps? What changes do I have to make at the maps/semantic-maps plugin?

**Comment by krabina** [comment]
sarting from line 133 in https://github.com/JeroenDeDauw/Maps/blob/master/includes/services/Leaflet/jquery.leaflet.js
you have to change the call for openlayers to something else, e.g. for basemap.at
L.TileLayer("http://{s}.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png", {maxZoom: 19, minZoom: 11, attribution: "Karte: Stadt Wien (<a href=\"http://data.wien.gv.at\" target=\"_blank\">data.wien.gv.at</a>)", subdomains: ["maps","maps1", "maps2", "maps3"], detectRetina: true}).addTo(map);

I am planning to make this configurable, so you can set the layers you want to be able to display in Localsettings.php...

**Comment by markmuzenhardt** [comment]
@krabina Thank you for this quick answer, this will save me a lot of time!

**Comment by krabina** [comment]
lerned that from https://twitter.com/mapsmarker

**Comment by JeroenDeDauw** [comment]
Own layers: https://github.com/JeroenDeDauw/Maps/pull/215
