### ISSUE TITLE
Marker cluster images are always retrieved over HTTP

### ISSUE THREAD

**Issue by AL286** [SemanticMediaWiki/SemanticMaps#34]
Using Semantic Maps 2.0.1.2.
Scenario: a semantic query using Google Maps output with the option markercluster=on.
The marker cluster image is always retrieved over HTTP, even if the map is being displayed in an HTTPS page.  This causes some browsers to report that the connection is not properly secured.

Responses to this Google Maps issue report may be pertinent:
https://code.google.com/p/google-maps-utility-library-v3/issues/detail?id=131
It says you should "set up your own styles array in the MarkerClustererOptions object".  Is this something that Semantic Maps could be doing when it calls Google Maps, to provide a protocol-relative path to the cluster images?

**Comment by PeterTheOne** [comment]
This should be fixed with https://github.com/JeroenDeDauw/Maps/pull/142 , can anyone check?

**Comment by kghbln** [comment]
@PeterTheOne Again, a good find! Do to the new PHP requirement I currently cannot directly test. However this should indeed be fixed. This one can still be reopened in worst-case.
