### ISSUE TITLE
Re-add lines parameter to the map format

### ISSUE THREAD

**Issue by acnetj** [SemanticMediaWiki/SemanticMaps#36]
Disappearance of lines and points parameters for semantic queries. The 2.X version allows the usage of lines and points from the map parser function to ask and compound queries functions. This provides the addition of lines with points provided by semantic queries.

The lines and points parameters continue to work under the display_map functions, but will be far more useful with semantic maps.

Example (v 2.X):  http://www.transitunlimited.org/San_Francisco_Bay_Ferry

Example (v 2.X): http://www.transitunlimited.org/Map:Metro_Bus_686 - this includes a semantic maps query and data provided from an external API.

**Comment by JeroenDeDauw** [comment]
Example:

```
{{#ask:[[-Ferry::<q>[[Provider::SF Bay Ferry]] OR [[Provider::San Francisco Bay Ferry]]</q>]]|?latlong|?-Ferry|icon=Ferry20.png|format=googlemaps|width=100%|height=400|lines=

{{#ask: [[Provider::SF Bay Ferry]][[line::+]] OR [[Provider::San Francisco Bay Ferry]][[line::+]]| ?line=|mainlabel=-|format=list|sep=;}}

}}
```

**Comment by JeroenDeDauw** [comment]
The "points" parameter is named "staticlocations", and has not been altered since version 2 as far as I know. https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/src/queryprinters/SM_MapPrinter.php#L60

**Comment by acnetj** [comment]
The problem with staticlocations (and points in the Maps) in this version is that it is very strict regarding ";" which is used to divide different locations. If there's an extra one before or after a location entry, it fails to work. The 2.X version was not that strict. 

Also, the custom icon doesn't work, which is also applies to the Maps extension. May be there's problem with Maps.

**Comment by JeroenDeDauw** [comment]
> The problem with staticlocations

Can you create distinct issues for distinct tasks?

> Also, the custom icon doesn't work, which is also applies to the Maps extension. May be there's problem with Maps.

Yeah. Looked at this yesterday and could not figure it out. https://github.com/JeroenDeDauw/Maps/issues/51

**Comment by PeterTheOne** [comment]
I vote for closing this issue. The custom Icon thing is talked about in https://github.com/JeroenDeDauw/Maps/issues/51 and @acnetj can open a new Issue about the problem with staticlocations..
