### ISSUE TITLE
"restricted" property doesn't work with map input in Semantic Maps

### ISSUE THREAD

**Issue by guoyunhe** [SemanticMediaWiki/SemanticMaps#40]
Semantic Forms has an input property `restricted`, which can restrict only admins can edit some fileds. But this doesn't work with map input.

I have set the "Location" input `restricted`, but users (not admin) can still change the coordinates and save it.

![semantic forms map input restrict](https://cloud.githubusercontent.com/assets/5836790/6187583/c8ef9410-b390-11e4-9dc8-ed322483dedb.png)

**Comment by JeroenDeDauw** [comment]
Yep, support for this feature was never added. Good idea though.

**Comment by JeroenDeDauw** [comment]
Now at https://github.com/JeroenDeDauw/Maps/issues/244
