### ISSUE TITLE
kml format / pagelinktext option does not work

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#41]
Just the plain text `Check out $1 now!` is passed to the query.

**Comment by JeroenDeDauw** [comment]
Thanks for reporting this issue

**Comment by kghbln** [comment]
I forgot to mention that I [changed the examples](https://semantic-mediawiki.org/w/index.php?title=Semantic_Maps_examples%2FKML_queries&diff=38169&oldid=22190) for the time being.

**Comment by JeroenDeDauw** [comment]
Now at https://github.com/JeroenDeDauw/Maps/issues/245
