### ISSUE TITLE
Issue adding shapes to semantic maps #ask: or using Special:Ask

### ISSUE THREAD

**Issue by megasquall** [SemanticMediaWiki/SemanticMaps#43]
When using {{#ask:}} queries, the "|polygons" or other shape attributes seem not to function correctly. Points for the request are displayed correctly, but shapes do not show off. Using the Speical:Ask form, the script shows the following error when setting any value to a shape input box :

Catchable fatal error: Object of class Maps\Elements\Polygon could not be converted to string in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\w\extensions\SemanticMediaWiki\includes\specials\SMW_SpecialAsk.php on line 437

The wiki is a fresh installation with the following configuration :

Windows 7
EasyPHP DevServer 14.1VC11
Apache 2.4.7
PHP 5.5.8 (apache2handler)
MySQL 5.6.15-log

MediaWiki 1.25.1
Maps 3.3
Semantic Maps 3.2
Semantic MediaWiki 2.2.1
Semantic Result Formats 2.1.2

That wiki is a local development server which you cannot access, but it was set up to reproduce the same problem we seem to have on a public wiki which you may access here : http://fr.scoutwiki.org/Special:Version. It is not the exact same environment, but they have the same version for MediaWiki and map / semantic extensions.

Any support would be appreciated.
Regards,

**Comment by JeroenDeDauw** [comment]
Is this about polygons defined on the map that displays queried coordinates, or is it about querying polygons?

**Comment by megasquall** [comment]
Hi, this is about polygons defined statically on a map that displays queried coordinates :

{{#ask: [[Category:Test]]
| ?GPS
| polygons = 1.2345,2.345:1.235,2.346:...
}}

**Comment by JeroenDeDauw** [comment]
In that case this overlaps with #36

**Comment by megasquall** [comment]
Isn't that one about querying polygons/shapes actually ?

I pushed my investigation forward, and it seems that the Maps\Elements\* and LatLongValue classes are missing a __toString() method so they can be used as strings in the SpecialAsk script at the specified line.

**Comment by JeroenDeDauw** [comment]
Right, it's something like that. The solution is not obvious though. SMW is assuming all these parameters are strings, which is not the case. And in Maps we can't add a `__toString` method with SMW specific output.

**Comment by megasquall** [comment]
I'm still starting to get my hands dirty on the code.

Looks like this function has to generate a valid {{ #ask: ... }} syntax by serializing information that was validated as a datamodel, to prevent invalid syntax or hack by injection. Seems quite legitimate. What you may be lacking is an adapter component that will serialize the datamodel object in a ask-compliant string format.

I would like to suggest some code for SpecialAsk.php, that would look like this, along with some DI pattern for the adapters :
```php
if(is_object($param))
{
  $paramType = get_class($param);
  $adapter = getSMWAskAdapter($paramType);
  return $adapter->serialize($param);
}
```

I can give a hand if required

**Comment by JeroenDeDauw** [comment]
Sorry for the late reply, I was on holiday. I've looked into this briefly and submitted https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/#1089 to improve the relevant type hints a bit.

You seem to have found a regression I introduced way back in https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/4df21015358dc37844f25a117883f0bd07d223cf

You made some good observations and I like your suggestion about having a list of value-to-ask-syntax-services injected. Unfortunately we do not have dedicated services for this, but rather have a `getSerialization` in `SMWDataItem`, the value base class.

I suspect this PR fixes the issue, though am not 100% sure it is correct (in particular that the names will always be present in this other array). I'd be helpful if you could have a look at that https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1090

**Comment by JeroenDeDauw** [comment]
Please reopen if not fixed
