### ISSUE TITLE
Cannot parse google map input data json

### ISSUE THREAD

**Issue by Karlpietsch** [SemanticMediaWiki/SemanticMaps#44]
"Loading map form input..."   is written in div of google map input, JSOn parsing fails
 
in  ext.sm.googlemapsinput.js
        $this.googlemapsinput($this.attr('id'), jQuery.parseJSON($this.find('div').text()));
should be 
        $this.googlemapsinput($this.attr('id'), jQuery.parseJSON($this.find('div.sminputdata').text()));

K

**Comment by JeroenDeDauw** [comment]
Thanks. I've made this change in https://github.com/SemanticMediaWiki/SemanticMaps/commit/546e6361284c74c0ec46838b9590e76e356321f4

As far as I can tell, the old code was not wrong though. It'd select the first div inside of the $this element, which is the correct one.

**Comment by Karlpietsch** [comment]
Thanks for such a quick response, I probably should have explained the issue better. The initial code works fine in most cases but not when the input is part of a multiple instance template it does not. The sminput div is wrapped in another sminput div.
e.g.

<div class="sminput sminput-googlemaps3" id="map_google3_3_forminput" style="display: inline;">Loading map form input...<div class="sminput sminput-googlemaps3" style="display: none;" data-origid="map_google3_3_forminput">Loading map form input...<div class="sminputdata" style="display: none;">{"type":"ROADMAP","mappingservice":"googlemaps3","geoservice":"geonames","types":["ROADMAP","SATELLITE","HYBRID","TERRAIN"],"width":"400px","height":"350px","centre":false,"zoom":14,"layers":[],"controls":["pan","zoom","type","scale","streetview"],"zoomstyle":"DEFAULT","typestyle":"DEFAULT","autoinfowindows":false,"resizable":false,"kmlrezoom":false,"poi":true,"markercluster":false,"tilt":0,"imageoverlays":[],"kml":[],"gkml":[],"fusiontables":[],"searchmarkers":"","enablefullscreen":false,"fieldsize":40,"icon":"","locations":[{"text":"","title":"","link":"","lat":-33.281328,"lon":149.096318,"alt":0,"address":"","icon":"","group":"","inlineLabel":"","visitedicon":""}],"geocodecontrol":true,"inputname":"Place[0a][Geo Coordinates]"}</div></div></div>

so the selector first finds outer div and grabs first div in that which is not the one with JSON data, the easiest fix was the one I sent you, changing the selector makes it work ok.

However there is an older issue with having the google maps input in a multi instance in that when you add a new instance the sminput  does not initialise with the JSON data, I made a bit of a hack code that waits a 100ms after new multi-instance template is added and initialises the JSON, see here https://github.com/SemanticMediaWiki/SemanticMaps/issues/25 
This is not a great solution, just a quick one. Might be better to add an event to the multi-instance template that fires when ready so any internal components that need initial setup such as semantic geo coord input can initialise.

K

**Comment by Karlpietsch** [comment]
```
<div class="sminput sminput-googlemaps3" id="map_google3_3_forminput" style="display: inline;">
	Loading map form input...
	<div class="sminput sminput-googlemaps3" style="display: none;" data-origid="map_google3_3_forminput">
		Loading map form input...
		<div class="sminputdata" style="display: none;">
			{"type":"ROADMAP","mappingservice":"googlemaps3","geoservice":"geonames","types":["ROADMAP","SATELLITE","HYBRID","TERRAIN"],"width":"400px","height":"350px","centre":false,"zoom":14,"layers":[],"controls":["pan","zoom","type","scale","streetview"],"zoomstyle":"DEFAULT","typestyle":"DEFAULT","autoinfowindows":false,"resizable":false,"kmlrezoom":false,"poi":true,"markercluster":false,"tilt":0,"imageoverlays":[],"kml":[],"gkml":[],"fusiontables":[],"searchmarkers":"","enablefullscreen":false,"fieldsize":40,"icon":"","locations":[{"text":"","title":"","link":"","lat":-33.281328,"lon":149.096318,"alt":0,"address":"","icon":"","group":"","inlineLabel":"","visitedicon":""}],"geocodecontrol":true,"inputname":"Place[0a][Geo Coordinates]"}
		</div>
	</div>
</div>

```

**Comment by JeroenDeDauw** [comment]
Thanks a lot for explaining!
