### ISSUE TITLE
Search Engines indexing JSON as content keywords

### ISSUE THREAD

**Issue by Karlpietsch** [SemanticMediaWiki/SemanticMaps#48]
Google indexes the JSON data in the map elements and adds bad content keywords to pages such as "u003"  and "href". I would highly recommend embedding the JSON data as a data attribute on the div rather than a hidden div inside the map element.

**Comment by JeroenDeDauw** [comment]
Thanks for the suggestion. Are there any catches with doing that? Such as it not working in older browsers?

**Comment by Karlpietsch** [comment]
Ok, maybe the simplest solution is to change the div with the map data in it to an input type=hidden field maybe then it won't be treated as page content to index. In the interim I added  googleon indexing directive comments around my maps to fix it but there is no single solution like that for all search engine crawlers.
I'd thought that hiding the DIV is enough but google crawler indexes all hidden content it seems now.

**Comment by Karlpietsch** [comment]
sorry, didn't mean to close that issue

**Comment by JeroenDeDauw** [comment]
Changing it to a data attribute is not hard - this requires some simple changes in the code of the Maps extension. I'm wondering if that will not cause problems though. You did not answer that question. Do you have an idea?

**Comment by Karlpietsch** [comment]
Here (http://caniuse.com/#feat=dataset) says data attribs not supported prior to IE8 etc.  

I actually just tried implementing it as a hidden input by changing Maps and Semantic Maps extensions but I highlighted another issue which may be the real cause of the problem with the indexing. 
The JSON data is not escaped correctly if you include an output property that is of type Page, so maybe this is why google crawler indexes it incorrectly.  If you have a page in the output parameters then it is put as a link but it is not escaped properly in JSON.  here is an example where I have  a property called "Suburb" that is of type page.  
You can see in the example below there is a link to "North Sydney" in the content that is not escaped. I can confirm that it is the "text" field in "locations" that is appearing in google search snippets and content keyword analytics.

Google Search results, showing JSON content retrieved for search snippet:
![invalid snippet](https://cloud.githubusercontent.com/assets/5679367/11229881/b1908f88-8de5-11e5-9a20-a04ab635dd28.png)

 
```javascript
{
  "format": "googlemaps3",
  "minzoom": false,
  "type": "ROADMAP",
  "types": [ "ROADMAP", "SATELLITE", "HYBRID", "TERRAIN" ],
  "maxzoom": false,
  "limit": 50,
  "offset": 0,
  "link": "all",
  "sort": [ "" ],
  "order": [ ],
  "headers": "show",
  "mainlabel": "",
  "intro": "",
  "outro": "",
  "searchlabel": "... further results",
  "default": "",
  "geoservice": "geonames",
  "width": "auto",
  "height": "350px",
  "centre": false,
  "zoom": 14,
  "layers": [ ],
  "controls": [ "pan", "zoom", "type", "scale", "streetview" ],
  "zoomstyle": "DEFAULT",
  "typestyle": "DEFAULT",
  "autoinfowindows": false,
  "resizable": false,
  "kmlrezoom": false,
  "poi": true,
  "markercluster": false,
  "tilt": 0,
  "imageoverlays": [ ],
  "kml": [ ],
  "gkml": [ ],
  "fusiontables": [ ],
  "searchmarkers": "",
  "enablefullscreen": false,
  "showtitle": true,
  "hidenamespace": false,
  "template": "",
  "activeicon": "",
  "pagelabel": false,
  "title": "",
  "label": "",
  "icon": "",
  "visitedicon": "",
  "lines": [ ],
  "polygons": [ ],
  "circles": [ ],
  "rectangles": [ ],
  "wmsoverlay": false,
  "copycoords": false,
  "static": false,
  "locations": [
    {
      "text": "\u003Cb\u003E\u003Ca href=\"/wiki/Mater_Hospital_Sydney\" title=\"Mater Hospital Sydney\"\u003EMater Hospital Sydney\u003C/a\u003E\u003C/b\u003E\u003Chr /\u003EMater Hospital Sydney\u003Cbr /\u003E25 Rocklands Road\u003Cbr /\u003E<a title="North
      Sydney" href="/wiki/North_Sydney">North Sydney</a>\u003Cbr /\u003E02 9900 7300",
      "title": "Mater Hospital Sydney",
      "link": "",
      "lat": -33.831441,
      "lon": 151.20145,
      "alt": 0,
      "address": "",
      "icon": "",
      "group": "",
      "inlineLabel": "",
      "visitedicon": ""
    }
  ]
}
```

**Comment by Karlpietsch** [comment]
solution: 
[SM_QueryHandler.php.txt](https://github.com/SemanticMediaWiki/SemanticMaps/files/37596/SM_QueryHandler.php.txt)

also in Maps extension,  in  jquery.googlemap.js  ln 86 
change 
`
text:$(markerData.text).text(),
`
to
`
text:$('<div>' + markerData.text + '</div>').text(),
`
when you convert some html string to a jquery object it should be in a wrapper DOM element as this fails under many circumstances unless the text is quite simple.

**Comment by JeroenDeDauw** [comment]
Moved to https://github.com/JeroenDeDauw/Maps/issues/237
