### ISSUE TITLE
Leaflet result format i18n missing

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMaps#53]
Can be seen on http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Ask

* maps_leaflet
* maps-leaflet-par-zoom
* maps-leaflet-par-defzoom
* maps-leaflet-par-resizable

**Comment by kghbln** [comment]
@JeroenDeDauw Ah, this is not not about adding the stings but making SM using the strings provided by the Maps extension?!

**Comment by kghbln** [comment]
Relates to https://github.com/JeroenDeDauw/Maps/issues/118

**Comment by JeroenDeDauw** [comment]
SM is already using specific message keys, the ones listed, which apparently are not defined yet. With the change in Maps merged, only `maps_leaflet` remains if I'm not mistaken

**Comment by kghbln** [comment]
I did not include "maps_leaflet" in my maps pull since it is [already there](https://github.com/JeroenDeDauw/Maps/search?utf8=%E2%9C%93&q=maps_leaflet) for quite some time. That's why I think an thought that SM is not using them for a reason. So basically why is "maps_leaflet" not showing up? Hmm...

**Comment by JeroenDeDauw** [comment]
Perhaps this was added after the latest release? Could just do 3.5 and see if it ends up fixing itself

**Comment by kghbln** [comment]
We are out of luck here since this will not help. sandbox runs master and this issue is there too.

**Comment by kghbln** [comment]
Composer cannot be serious: Maps	3.4.1 (05e6e0b) 16:31, 30 January 2016 because of @dev????????? No time for this now. Just one day without bull... Would be very nice indeed.

**Comment by kghbln** [comment]
@JeroenDeDauw See: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1186#issuecomment-204390186 - So yes, doing a new release would have done the magic. Now forced the wiki to use master.
