### ISSUE TITLE
Rendering issues in case templates are used for custom formatting

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#56]
I just see yellow snow when trying to display a google maps v3 map. Some API-change at Google which requires this extension to be adapted?

Instead of a Map one gets the message "Your browser is not compatible with Google Maps v3".

[Directly added maps](https://www.semantic-mediawiki.org/wiki/Maps_examples/Google_Maps_basic_map) are cool. As soon as [SM is used](https://www.semantic-mediawiki.org/wiki/Semantic_Maps_examples/Using_templates_%28queries%29) I just see this error message (all browsers).

**Comment by JeroenDeDauw** [comment]
Is this issue still present with SM 3.3.x?

**Comment by kghbln** [comment]
Just tried. It is indeed still an issue. :( I was however just able to narrow it down to the usage of templates for custom formatting.

**Comment by JeroenDeDauw** [comment]
Can this be closed?

**Comment by kghbln** [comment]
Cannot tell right now since the reference page for this issue suffers from https://github.com/JeroenDeDauw/Maps/issues/246

**Comment by JeroenDeDauw** [comment]
Issue is still present with SM 3.4.1

**Comment by JeroenDeDauw** [comment]
Moving to https://github.com/JeroenDeDauw/Maps/issues/248
