### ISSUE TITLE
Make two locations with the same coordinates distinguishable

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#65]
Currently it is not possible to distinguish two locations with the same coordinates distinguishable i.e. a query like e.g.
```text
{{#ask:
 [[Category:Location]]
 [[Has coordinates::+]]
 |?Has coordinates
 |format=map
}}
```
renders only the first location no matter how close I zoom in. It will be nice to be able to get tow markers instead of just the first one.

See a live example on [sandbox.smw.o](http://sandbox.semantic-mediawiki.org/wiki/Locations) for this.

**Comment by PeterTheOne** [comment]
Close this issue and have a look at https://github.com/JeroenDeDauw/Maps/issues/39.

**Comment by kghbln** [comment]
Ops, you are right. This is a dupe.
