### ISSUE TITLE
SemanticMaps not working

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#66]
Transferred from https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1547

### Setup and configuration

- SMW version: 3.5
- MW version: 1.26.2
- PHP version: 5.6.20-0+deb8u1 (apache2handler)
- MySQL 	5.5.47-0+deb8u1

### Issue
 HiI have installed the mediawiki, the SemanticMaps and all the dependencies but the extension is not working.For your reference I am sending you the below ink

http://mediawiki.convergence.solutions/index.php/Test_page do not get any error in the logs.The 

Maps extension is working without a problem. I would appreciate your help and any idea that you might have.
Thanks a lot
George

**Comment by kghbln** [comment]
The issue is not very specific at all and since you are referring to a version 3.5 it may be that Semantic Maps is perhaps not installed at all. Additionally you are referring to a closed wiki. Perhaps you may want ot (whitelist)[https://www.mediawiki.org/wiki/Manual:$wgWhitelistRead] this page.

1. Did you create properties of type geographical coordinates?
2. Is your semantic query working?

@gnikoloudis

**Comment by gnikoloudis** [comment]
Hi
Thanks for your reply
I have whitelist the page you can now see that I have installed the SemanticMaps.
I am trying to check if the semantic queries are working. Any example that I can use?
Thanks!

**Comment by gnikoloudis** [comment]
hi 

I tried to create a class and I am getting the following:

[Thu May 05 05:17:41.324430 2016] [:error] [pid 17947] [client 139.193.134.100:63849] PHP Fatal error:  Call to a member function getNamespace() on null in /var/www/mediawiki/includes/jobqueue/JobQueueDB.php on line 728, referer: http://mediawiki.convergence.solutions/index.php/Special:CreateClass

An idea?
is it php issue?

thanks

**Comment by mwjames** [comment]
> PHP Fatal error: Call to a member function getNamespace() on null in /var/www/mediawiki/includes/jobqueue/JobQueueDB.php on line 728, referer: http://mediawiki.convergence.solutions/index.php/Special:CreateClass

Skimming Google uncovers [0] for the mentioned issue (which does not really relate to SM or SMW).

[0] https://www.mediawiki.org/wiki/Extension_talk:Semantic_Forms/Archive_February_to_March_2015#Special:CreateClass:_getNamespace_error_in_JobQueueDB_with_SF_2.7

**Comment by gnikoloudis** [comment]
Hi With the addition of settings in the LocalSettings.php file the problem fixed. However is there a permanent fix on this ? Is there something I can do?

**Comment by mwjames** [comment]
> With the addition of settings in the LocalSettings.php file the problem fixed.

@gnikoloudis Just to clarify, `enableSemantics` has been added to your LocalSettings as mentioned in [0, 1]?

[0] https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.22_-_1.24
[1] https://www.semantic-mediawiki.org/wiki/Help:Installation/Using_Composer_with_MediaWiki_1.25%2B

**Comment by gnikoloudis** [comment]
Yes 
enableSemantics( 'mediawiki.convergence.solutions' )
is enabled at the end of the LocalSettings.php

**Comment by kghbln** [comment]
I assume there is a colon after ` enableSemantics( 'mediawiki.convergence.solutions' )`

The third question still unanswered will be:

3. Do you see Semantic Maps on special page "Special:Version"

I still cannot access the test page. However I have prepared a simple example on how to use Semantic maps on a [sandbox wiki](http://sandbox.semantic-mediawiki.org/wiki/Simple_query_for_locations), so go through these pages recreate them on your wiki an it should work.

**Comment by gnikoloudis** [comment]
I whitelist the page, the link is the below.  
http://mediawiki.convergence.solutions/index.php/Test_page
I have also whitelist the Special:Version page.

I copied the code from your page example, but still no result. I recreate the page Athens just for example.


Just let me know I am doing something wrong.

Thanks for your support

**Comment by kghbln** [comment]
Looks fine to me. Semantic Maps is installed and the property annotations are cool too. So far you failed to create the property "Has coordinates" of type geographical coordinates. Follow the link to the property on the sandbox wiki to see how it is done.

**Comment by mwjames** [comment]
> So far you failed to create the property "Has coordinates" of type geographical coordinates. Follow the link to the property on the sandbox wiki to see how it is done. Semantic Maps only picks

https://www.semantic-mediawiki.org/wiki/Help:Getting_started/Using_geographic_coordinates

**Comment by gnikoloudis** [comment]
I created the property "has coordinates" and "has area", and I created the pages: http://mediawiki.convergence.solutions/index.php/SemanticMapsExample
http://mediawiki.convergence.solutions/index.php/SemanticQueriesExample
And it seems to work.

What I understand is that I need to create the property that I am going to be used in the pages. One question on naming the properties, is it better the use names like "Has name" or "Name".

Thanks a lot for the support

 George

**Comment by kghbln** [comment]
>  And it seems to work.

It does work.

As to the naming of properties: Make them unambiguous both in naming and usage and you will be fine, so I would prefer "Has name" over "Name". How you do this in your environment is basically up to you.
