### ISSUE TITLE
Map does not display on Special:Ask

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMaps#67]
https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk&q=[[Has+coordinates%3A%3A%2B]]&po=%3FHas+coordinates&eq=yes&p[format]=googlemaps3&sort_num=&order_num=ASC&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=...+further+results&p[default]=&p[geoservice]=geonames&p[width]=auto&p[height]=350&p[centre]=&p[zoom]=14&p[type]=roadmap&p[zoomstyle]=default&p[typestyle]=default&p[poi]=1&p[tilt]=0&p[imageoverlays]=&p[kml]=&p[gkml]=&p[fusiontables]=&p[searchmarkers]=&p[staticlocations]=&p[showtitle]=1&p[template]=&p[userparam]=&p[activeicon]=&p[title]=Special%3AAsk&p[label]=&p[icon]=&p[visitedicon]=&p[lines]=&p[polygons]=&p[circles]=&p[rectangles]=&p[wmsoverlay]=&p[maxzoom]=&p[minzoom]=&eq=yes

* Go to https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk
* `[[Has coordinates::+]]`
* `?Has coordinates`
* Google Maps v3
* Find results

**Comment by JeroenDeDauw** [comment]
Does not occur on sandbox... http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AAsk&q=[[Has+coordinates%3A%3A%2B]]&po=%3FHas+coordinates%0D%0A&eq=yes&p[format]=googlemaps3&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=%26hellip%3B+autres+r%C3%A9sultats&p[default]=&p[geoservice]=geonames&p[width]=auto&p[height]=350&p[centre]=&p[zoom]=14&p[type]=roadmap&p[zoomstyle]=default&p[typestyle]=default&p[poi]=1&p[tilt]=0&p[imageoverlays]=&p[kml]=&p[gkml]=&p[fusiontables]=&p[searchmarkers]=&p[staticlocations]=&p[showtitle]=1&p[template]=&p[userparam]=&p[activeicon]=&p[title]=&p[label]=&p[icon]=&p[visitedicon]=&p[lines]=&p[polygons]=&p[circles]=&p[rectangles]=&p[wmsoverlay]=&p[maxzoom]=&p[minzoom]=&eq=yes

**Comment by mwjames** [comment]
> Go to https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk

I'm guessing an exception is raised on the www.semantic-mediawiki.org and not shown.

> Does not occur on sandbox...

which is fixed on the sandbox. Most likely related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1473
