### ISSUE TITLE
add ajaxquery examples to semantic-mediawiki.org

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticMaps#71]

**Comment by JeroenDeDauw** [comment]
This wiki is running stable versions of the extensions, so a release of SM needs to happen before you can put examples there.

**Comment by mwjames** [comment]
Probably add some to http://sandbox.semantic-mediawiki.org since it is running on `"mediawiki/semantic-maps": "@dev"` and any issues can be caught before making a release.

**Comment by kghbln** [comment]
> Probably add some to http://sandbox.semantic-mediawiki.org since it is running on "mediawiki/semantic-maps": "@dev" and any issues can be caught before making a release.

+1 As soon as I updated semantic-mediawiki.org these examples could be imported from sandbox

**Comment by PeterTheOne** [comment]
Yes, of course first sandbox then semantic-mediawiki.org ;)

**Comment by PeterTheOne** [comment]
http://sandbox.semantic-mediawiki.org/wiki/Ajaxquery

Feel free to modify it.

**Comment by kghbln** [comment]
Could you add an example showing the bahaviour without the ajaxquery. So far I do not really see that this feature is all about.

**Comment by JeroenDeDauw** [comment]
Guess it is kinda hard to demonstrate the difference, since the whole point is that it looks the same to the user... apart from the page source getting huge when there are many results.

**Comment by kghbln** [comment]
Indeed I just had another look at the page and figured out that it must be a performance feature. Makes sense now. Sorry I am dancing on multiple parties today so I got confused. :( As soon as SM 2.4 is released I will transfer the example to smw.o and add more fluff.

**Comment by PeterTheOne** [comment]
@kghbln I guess the example was not clear enough :P

**Comment by PeterTheOne** [comment]
I added another example without ajax, but it is broken because of #90.
