### ISSUE TITLE
3.4 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMaps#76]
Blockers
* [x] OpenLayers does not show up https://github.com/SemanticMediaWiki/SemanticMaps/issues/77
* [x] False positive compound query detection https://github.com/SemanticMediaWiki/SemanticMaps/pull/106

And possibly:

* [x] OpenLayers result format auto-zoom is broken https://github.com/SemanticMediaWiki/SemanticMaps/issues/80

Release notes TODO:

* [ ] Elaborate Dynamic loading of markers section, either including a brief example or linking to one on SMW wiki or sandbox
* [x] Go over merged changes since last rel, as this list was definitely not complete yet

**Comment by JeroenDeDauw** [comment]
@PeterTheOne Can you reword `Added autoload location data with Ajax feature` in the release notes to something non technical users can understand? Adding a link to an example would also be real cool.

**Comment by PeterTheOne** [comment]
Ok, sure.

**Comment by PeterTheOne** [comment]
Example is here now: http://sandbox.semantic-mediawiki.org/wiki/Ajaxquery

How about: `Added Ajaxquery: Dynamically load points when moving or zooming map`?

**Comment by PeterTheOne** [comment]
Before releasing we should have a look at #77, also @Flexmaen reported an issue with SemanticForms on some Mailinglist.

**Comment by Flexmaen** [comment]
Yes. The error message in this mail is not related to the map.

However, with Semantic Maps 3.3 the map input for coordinates with Semantic Forms worked, with Semantic Maps 3.4-alpha it didn't work anymore.

Maybe someone could check if this really is related to the update.

**Comment by kghbln** [comment]
REM: Transfer example for https://github.com/SemanticMediaWiki/SemanticMaps/issues/71 from sandbox to www.

**Comment by PeterTheOne** [comment]
The SemanticForms Issue #84 is resolved.

**Comment by PeterTheOne** [comment]
Fix/Merge these before release #77 #95 #98?

**Comment by JeroenDeDauw** [comment]
Definitely blocker: #80

**Comment by JeroenDeDauw** [comment]
I've updated the blockers

**Comment by JeroenDeDauw** [comment]
@kghbln actually I'm not sure the OpenLayers issue is a blocker. It should be fixed yes. However if it was already broken in the previous release, we don't make things worse by not having it fixed in the next one. So any idea if it was present in 3.3?

**Comment by JeroenDeDauw** [comment]
Thanks to Wikiapiary I was able to confirm the absence of the bug in SM 3.3: http://www.bacid.eu/Special:Ask

**Comment by kghbln** [comment]
> So any idea if it was present in 3.3?
No, [it was not](https://www.semantic-mediawiki.org/wiki/User:Kghbln/test). Judging by the importance of the format I thing a fix will be great.

**Comment by JeroenDeDauw** [comment]
@PeterTheOne @kghbln any good docs on the new dynamic loading feature that can be linked yet? That section of the readme needs some fluff. Once that'd done we can finally get this release out of the door.

**Comment by JeroenDeDauw** [comment]
@PeterTheOne did you add any dependencies on recent version of SMW, or does SM still work with SMW 2.0?

**Comment by PeterTheOne** [comment]
@JeroenDeDauw Dependencies: I don't think I added any new SMW dependencies. I developed with versions between `~2.3.1` and `dev-master`. Only #72 would have added new dependencies.

**Comment by PeterTheOne** [comment]
@JeroenDeDauw There is http://sandbox.semantic-mediawiki.org/wiki/Ajaxquery (but it needs the newest versions of Maps, SemanticMaps and SemanticCompoundQueries to work).

**Comment by JeroenDeDauw** [comment]
So the new dynamic loading feature will be broken unless you have the latest stable versions of these extensions?

**Comment by PeterTheOne** [comment]
@JeroenDeDauw The currently installed (not stable) version of Semantic Maps has the bug where it confuses ask queries for compound queries. For compound queries it needs the compound query api that was added in the not yet released SemanticCompoundQueries version. Maps 3.8 should is good.

**Comment by JeroenDeDauw** [comment]
So the only thing that will fail when running SM 3.4 with Maps 3.8, SMW 3.4 and latest SQC is dynamic compound queries?

**Comment by PeterTheOne** [comment]
correct.

**Comment by JeroenDeDauw** [comment]
Yeah that one :D

Ok, then the only blocker left is the proper outlining of the dynamic loading feature in the release notes

**Comment by JeroenDeDauw** [comment]
@PeterTheOne I'm basically waiting for you to tackle that :)

**Comment by JeroenDeDauw** [comment]
> There is http://sandbox.semantic-mediawiki.org/wiki/Ajaxquery

The example there is broken; it is using the compoundquery API even though it's not a compound query

**Comment by JeroenDeDauw** [comment]
Due to the bug I've removed the addition of this feature from the release notes. We can announce it in the next release when it works. https://github.com/SemanticMediaWiki/SemanticMaps/pull/117

**Comment by PeterTheOne** [comment]
ok sure.
