### ISSUE TITLE
OpenLayers result format auto-zoom is broken

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMaps#80]
~~No results are rendered then searching for results with~~
```
{{#ask:
 [[Category:Sample pages]]
 |?Has coordinates
 |format=openlayers
}}
```
whereas `format=googlemaps` shows the expected results. See on the [example page](http://sandbox.semantic-mediawiki.org/wiki/Issue/80_(SM)) on sandbox.smw.

**Comment by PeterTheOne** [comment]
The map shows results, it is just zoomed into the ocean and not centered correctly.

**Comment by kghbln** [comment]
> The map shows results, it is just zoomed into the ocean and not centered correctly.

Ah, this used to be the behaviour when no results were found. So I did not look further. So the autozooming appears somehow broken?

**Comment by PeterTheOne** [comment]
Seems so.

**Comment by JeroenDeDauw** [comment]
Can it be that the OL format was disabled on the sandbox for some reason? It's not showing up on Special:Ask, and this would explain why its falling back to google maps.

**Comment by kghbln** [comment]
No, the settings in "LocalSettings.php" on sandbox:

```php
## Maps
// Composer
$egMapsEnableCategory = false;

## SemanticMaps
// Composer
```

**Comment by JeroenDeDauw** [comment]
Does this issue also happen on other wikis? My guess is still that the format is not enabled. Perhaps some code change accidentally broke registration of the thing?

**Comment by PeterTheOne** [comment]
On my development wiki I have the same issue for some time now.

**Comment by mwjames** [comment]
```
MapsMappingServices::registerServiceFeature( 'openlayers', 'qp', 'SMMapPrinter' );
```
Above is missing in [0], somehow it got lost between merges (see [1]).

[0] https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/src/services/OpenLayers/SM_OpenLaysers.php

[1] https://github.com/SemanticMediaWiki/SemanticMaps/commit/5e097c01c605086209359b8ac473a48abe987cc8#diff-0b3bd45d437aca0dfa0e5dfc6b1caafbR73

**Comment by PeterTheOne** [comment]
PR incoming ;)

**Comment by JeroenDeDauw** [comment]
@kghbln do you still see this issue?

**Comment by kghbln** [comment]
> do you still see this issue?

Dunno, since currently "openlayers" renders as "googlemaps" due to https://github.com/SemanticMediaWiki/SemanticMaps/issues/77

**Comment by JeroenDeDauw** [comment]
Anyone know if this is a regression since 3.3, or did that release also include the bug?

**Comment by PeterTheOne** [comment]
@JeroenDeDauw As far as I know this bug was not present in 3.3 and it is likely that I introduced it somewhere along the way ^^

**Comment by PeterTheOne** [comment]
This bug applies also to Maps `display_map` with more than one point. Also I don't understand how this has worked before..

**Comment by PeterTheOne** [comment]
It worked in Maps 3.6

**Comment by PeterTheOne** [comment]
PR incoming ^^
