### ISSUE TITLE
Ajax-requests for obsolete zoom levels when zooming in and out

### ISSUE THREAD

**Issue by Flexmaen** [SemanticMediaWiki/SemanticMaps#82]
You can try that at
http://www.housetrails.org/index.php?title=Hauptplatz_1&Lang=EN

Just use your mousewheel to zoom out, count the steps the map made. If you finished zooming and you had three steps, then markes will reload three times, although the zooming process already has stopped.
They seem to load for all the zoomlevels you skipped before.
I think the request should only process your "final destination".

**Comment by PeterTheOne** [comment]
Thanks for the report, this line https://github.com/SemanticMediaWiki/SemanticMaps/blob/master/src/services/GoogleMaps3/ext.sm.googlemaps3ajax.js#L37 should have prevented this. I will check it out.
