### ISSUE TITLE
Form input broken

### ISSUE THREAD

**Issue by Flexmaen** [SemanticMediaWiki/SemanticMaps#84]
We were using a input field for coordinates in Semantic Forms, like
```text
{{{field|Coordinates|input type=googlemaps|default={{PAGENAME}}|property=Coordinates|mandatory}}}
```
(I think "Coordinates" here is a variable specified in the own system)

This input field loaded with Semantic Maps 3.3 but didn't load with 3.4.0-alpha.
Maybe you could check if some change caused a problem.
BTW: input type didn't work with leaflet or openlayers  in the older versions anyway, so you always had to use google maps.

**Comment by PeterTheOne** [comment]
> MWException from line 811 of /vagrant/mediawiki/includes/resourceloader/ResourceLoaderFileModule.php: ResourceLoaderFileModule::readScriptFiles: script file not found: "/vagrant/mediawiki/extensions/SemanticMaps/src/jquery.mapforminput.js"

Is what I get as an Exception. The Files is located in `mediawiki/extensions/SemanticMaps/src/mapforminput/jquery.mapforminput.js` and I don't know why it is looking in `mediawiki/extensions/SemanticMaps/src/jquery.mapforminput.js`.
