### ISSUE TITLE
Leaflet fullscreen

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticMaps#86]
Hello,

It would be nice to be able to use `enablefullscreen` with Leaflet.
There is a nice plugin that does that: https://github.com/brunob/leaflet.fullscreen

**Comment by PeterTheOne** [comment]
Thanks for the Issue, this feature should be implement in https://github.com/JeroenDeDauw/Maps .

**Comment by kghbln** [comment]
@Rudloff Thanks for adding 100 and relocating to Maps. :)
