### ISSUE TITLE
Leaflet tile layer URL

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticMaps#87]
Hello,

It would be useful to be able to set the tile layer URL for Leaflet.
Currently we can't choose anything else than OSM.

**Comment by PeterTheOne** [comment]
Thanks for the Issue, this feature should be implement in https://github.com/JeroenDeDauw/Maps .

**Comment by kghbln** [comment]
@Rudloff Thanks for relocating to Maps.
